name: Feed Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - run: pip3 install -r requirements.txt
      - run: python task.py
      - name: Commit and push if changed
        run: |-
          git config user.name "Actions on behalf of Devon Ankar"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
